---
AWSTemplateFormatVersion: "2010-09-09"
Description: 
  Infrastructure resources to support the RestBugs v2 api server
Resources:
  BugsTable:
    Type: AWS::DynamoDB::Table
    Properties:
        # per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html, only specifying significant attributes needed for indexing
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
            - AttributeName: id
              KeyType: HASH
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
            - AttributeName: id
              KeyType: HASH

Outputs:
    BugsTableID:
        Value: !Ref BugsTable
    UsersTableID:
        Value: !Ref UsersTable

# aws cloudformation deploy --stack-name ps-rest-fun --template-file template.yaml --profile ps-rest-fun
